#include "strings.h"
#include <stdint.h>

char* global_string[NUM_STRINGS]= {
     (char*)"Are you sure you want to exit?",
     (char*)"Are you sure?",
     (char*)"Yes",
     (char*)"No",
     (char*)"OK",
     (char*)"Cancel",
     (char*)"Enter new name:",
     (char*)"  DEVICE  ",
     (char*)"F1 Next",
     (char*)"F2 Refresh",
     (char*)"F3 Format",
     (char*)"Drive #%u",
     (char*)"   FILE   ",
     (char*)"C <<<<<<<<",
     (char*)"C >>>>>>>>",
     (char*)"X Delete",
     (char*)"D Duplicat",
     (char*)"R Rename",
     (char*)"T Txt View",
     (char*)"H Hex View",
     (char*)"Scanning for drives...",
     (char*)"%u drives found",
     (char*)"Files sorted by name",
     (char*)"Files sorted by size",
     (char*)"Files sorted by type",
     (char*)"Formatting...",
     (char*)"Copying...",
     (char*)"Deleting...",
     (char*)"Reading directory...",
     (char*)"Delete file?",
     (char*)"File deleted",
     (char*)"Unable to delete file",
     (char*)"Done",
     (char*)"(More)",
     (char*)"Hit any key",
     (char*)"****** Hex view of '%s' -- Hit SPACE for more; Esc to stop ******",
     (char*)"****** Text view of '%s' -- Hit SPACE for more; Esc to stop ******",
     (char*)"DIR",
     (char*)"PRG",
     (char*)"REL",
     (char*)"SEQ",
     (char*)" d ",
     (char*)"oth",
     (char*)"Fatal error, program cannot continue. Error %u",
     (char*)"The disk is full",
     (char*)"A disk error occurred",
     (char*)"Error: Could not open file",
     (char*)"Error: Could not list directory",
     (char*)"f/Manager",
     (char*)"f/Manager B128",
     (char*)"version %u.%u.%u",
     (char*)"Copyright Micah Bly, 2023",
     (char*)"Cross-compiler: cc65",
     (char*)"Editor: BBEdit (the greatest of them all)",
     (char*)"This program is open source, using GPL 3 license. Please share improvements!",
     (char*)"https://github.com/WartyMN/B128-fmanager/",
     (char*)"Thanks to Steve Gray, Jim Brain, the godz on CBM-Hackers, and everyone who",
     (char*)"keeps these old machines going!",
};
